version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hits-analysis-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ziiulx9pavvf"
s3_prefix = "hits-analysis-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
